#!/bin/bash

# Dynamically creates a dotfile for stow to use.

# the dotfile
cfg=~/.stow-cfg

# stow_config repo root
stowdir=$(pwd)

echo "export STOW_DIR=$stowdir" > $cfg;
echo "Done. source $cfg to and you're set";
