(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by mds, created 2017-07-14."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "Grey15")
      (background-mode . dark)
      (border-color . "Grey")
      (cursor-color . "#005F87")
      (foreground-color . "Grey")
      (mouse-color . "Grey"))
     ((align-highlight-change-face . highlight)
      (align-highlight-nochange-face . secondary-selection)
      (apropos-match-face . match)
      (compilation-message-face . underline)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . bold)
      (list-matching-lines-prefix-face . shadow)
      (org-goto-interface . outline)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 143 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (Info-quoted ((t (:family "courier"))))
     (Man-overstrike ((t (:bold t :weight bold))))
     (Man-reverse ((t (:background "dark slate blue" :foreground "light blue"))))
     (Man-underline ((t (:underline t))))
     (airline-emacs-center ((t (:background "#5d478b" :foreground "#EEEEEE"))))
     (airline-emacs-inner ((t (:background "#8968cd" :foreground "#E4E4E4"))))
     (airline-emacs-outer ((t (:background "#E4E4E4" :foreground "#585858"))))
     (airline-inactive3 ((t (:background "#324E59" :foreground "#EEEEEE"))))
     (airline-insert-center ((t (:background "#2E8700" :foreground "#EEEEEE"))))
     (airline-insert-inner ((t (:background "#47AF00" :foreground "#E4E4E4"))))
     (airline-insert-outer ((t (:background "#E4E4E4" :foreground "#585858"))))
     (airline-normal-center ((t (:background "#005F87" :foreground "#EEEEEE"))))
     (airline-normal-inner ((t (:background "#0087AF" :foreground "#E4E4E4"))))
     (airline-normal-outer ((t (:background "#E4E4E4" :foreground "#585858"))))
     (airline-replace-center ((t (:background "#875300" :foreground "#EEEEEE"))))
     (airline-replace-inner ((t (:background "#AF5F00" :foreground "#E4E4E4"))))
     (airline-replace-outer ((t (:background "#E4E4E4" :foreground "#585858"))))
     (airline-visual-center ((t (:background "#872800" :foreground "#EEEEEE"))))
     (airline-visual-inner ((t (:background "#AF2800" :foreground "#E4E4E4"))))
     (airline-visual-outer ((t (:background "#E4E4E4" :foreground "#585858"))))
     (apropos-function-button ((t (:bold t :foreground "aquamarine" :weight bold))))
     (apropos-keybinding ((t (:underline t))))
     (apropos-misc-button ((t (:foreground "pale green"))))
     (apropos-property ((t (:foreground "aquamarine"))))
     (apropos-symbol ((t (:bold t :weight bold))))
     (apropos-user-option-button ((t (:bold t :foreground "turquoise" :weight bold))))
     (apropos-variable-button ((t (:bold t :foreground "turquoise" :weight bold))))
     (avy-background-face ((t (:foreground "gray40"))))
     (avy-goto-char-timer-face ((t (:background "dark slate blue" :foreground "light blue"))))
     (avy-lead-face ((t (:background "#e52b50" :foreground "white"))))
     (avy-lead-face-0 ((t (:background "#4f57f9" :foreground "white"))))
     (avy-lead-face-1 ((t (:background "gray" :foreground "white"))))
     (avy-lead-face-2 ((t (:background "#f86bf3" :foreground "white"))))
     (bg:erc-color-face0 ((t (nil))))
     (bg:erc-color-face1 ((t (nil))))
     (bg:erc-color-face10 ((t (nil))))
     (bg:erc-color-face11 ((t (nil))))
     (bg:erc-color-face12 ((t (nil))))
     (bg:erc-color-face13 ((t (nil))))
     (bg:erc-color-face14 ((t (nil))))
     (bg:erc-color-face15 ((t (nil))))
     (bg:erc-color-face2 ((t (nil))))
     (bg:erc-color-face3 ((t (nil))))
     (bg:erc-color-face4 ((t (nil))))
     (bg:erc-color-face5 ((t (nil))))
     (bg:erc-color-face6 ((t (nil))))
     (bg:erc-color-face7 ((t (nil))))
     (bg:erc-color-face8 ((t (nil))))
     (bg:erc-color-face9 ((t (nil))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:bold t :foreground "beige" :weight bold))))
     (border ((t (:background "Grey"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:foreground "cyan1" :underline t))))
     (c-annotation-face ((t (:foreground "pale green"))))
     (calendar-month-header ((t (:bold t :foreground "aquamarine" :weight bold))))
     (calendar-today ((t (:underline t))))
     (calendar-today-face ((t (:underline t))))
     (calendar-weekday-header ((t (:foreground "pale green"))))
     (calendar-weekend-header ((t (:foreground "light blue"))))
     (change-log-acknowledgment ((t (:foreground "light blue"))))
     (change-log-conditionals ((t (:bold t :weight bold :foreground "turquoise"))))
     (change-log-date ((t (:foreground "light sky blue"))))
     (change-log-email ((t (:bold t :weight bold :foreground "turquoise"))))
     (change-log-file ((t (:bold t :weight bold :foreground "aquamarine"))))
     (change-log-function ((t (:bold t :weight bold :foreground "turquoise"))))
     (change-log-list ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (change-log-name ((t (:foreground "pale green"))))
     (cider-deprecated-face ((t (:background "#432"))))
     (cider-docview-emphasis-face ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :weight normal :slant normal :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :underline t :height 143))))
     (cider-docview-literal-face ((t (:foreground "light sky blue"))))
     (cider-docview-strong-face ((t (:bold t :family "DejaVu Sans Mono" :foundry "PfEd" :width normal :slant normal :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :underline t :weight bold :height 143))))
     (cider-docview-table-border-face ((t (:foreground "grey70"))))
     (cider-error-highlight-face ((t (:underline (:style wave :color "red")))))
     (cider-fragile-button-face ((t (:bold t :weight bold :foreground "Red" :box (:line-width 3 :style released-button)))))
     (cider-fringe-good-face ((t (:foreground "darkgreen"))))
     (cider-instrumented-face ((t (:box (:color "#c00" :line-width -1)))))
     (cider-reader-conditional-face ((t (:foreground "light blue"))))
     (cider-repl-input-face ((t (:bold t :weight bold))))
     (cider-repl-prompt-face ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (cider-repl-result-face ((t (nil))))
     (cider-repl-stderr-face ((t (:bold t :weight bold :foreground "Red"))))
     (cider-repl-stdout-face ((t (:foreground "light sky blue"))))
     (cider-result-overlay-face ((t (:background "grey10" :box (:line-width -1 :color "black")))))
     (cider-stacktrace-error-class-face ((t (:bold t :weight bold :foreground "Red"))))
     (cider-stacktrace-error-message-face ((t (:foreground "light sky blue"))))
     (cider-stacktrace-face ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :height 143))))
     (cider-stacktrace-filter-hidden-face ((t (:underline t :foreground "cyan1" :underline nil :weight normal))))
     (cider-stacktrace-filter-shown-face ((t (:foreground "cyan1" :underline t :weight normal))))
     (cider-stacktrace-fn-face ((t (:bold t :family "DejaVu Sans Mono" :foundry "PfEd" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :weight bold :height 143))))
     (cider-stacktrace-ns-face ((t (:foreground "light blue"))))
     (cider-stacktrace-promoted-button-face ((t (:bold t :weight bold :foreground "Pink" :box (:line-width 3 :style released-button)))))
     (cider-stacktrace-suppressed-button-face ((t (:foreground "dim gray" :box (:line-width 3 :style pressed-button)))))
     (cider-test-error-face ((t (:background "orange4"))))
     (cider-test-failure-face ((t (:background "firebrick"))))
     (cider-test-success-face ((t (:background "green" :foreground "black"))))
     (cider-traced-face ((t (:box (:color "cyan" :line-width -1)))))
     (cider-warning-highlight-face ((t (:underline (:style wave :color "yellow")))))
     (clojure-character-face ((t (:foreground "light sky blue"))))
     (clojure-interop-method-face ((t (:foreground "aquamarine"))))
     (clojure-keyword-face ((t (:foreground "pale green"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (company-echo ((t (nil))))
     (company-echo-common ((t (:foreground "firebrick1"))))
     (company-preview ((t (:background "blue4" :foreground "wheat"))))
     (company-preview-common ((t (:background "blue4" :foreground "red"))))
     (company-preview-search ((t (:background "blue1" :foreground "wheat"))))
     (company-scrollbar-bg ((t (:background "gold"))))
     (company-scrollbar-fg ((t (:background "red"))))
     (company-template-field ((t (:background "yellow" :foreground "black"))))
     (company-tooltip ((t (:background "yellow" :foreground "black"))))
     (company-tooltip-annotation ((t (:foreground "red4"))))
     (company-tooltip-annotation-selection ((t (:foreground "red4"))))
     (company-tooltip-common ((t (:foreground "red"))))
     (company-tooltip-common-selection ((t (:foreground "red"))))
     (company-tooltip-mouse ((t (:background "dark slate blue" :foreground "light blue"))))
     (company-tooltip-search ((t (:background "dark slate blue" :foreground "light blue"))))
     (company-tooltip-search-selection ((t (:background "dark slate blue" :foreground "light blue"))))
     (company-tooltip-selection ((t (:background "orange1"))))
     (compilation-column-number ((t (:foreground "light sky blue"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:foreground "sky blue"))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cperl-array-face ((t (:bold t :foreground "light salmon" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "aquamarine"))))
     (cursor ((t (:background "#005F87"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-face ((t (:foreground "gainsboro"))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-changed-face ((t (:background "blue" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-face ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-comment-tag-face ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-documentation-face ((t (:foreground "light blue"))))
     (custom-face-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-face-tag-face ((t (:underline t))))
     (custom-group-subtitle ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "helv"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "helv"))))
     (custom-group-tag-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (custom-group-tag-face-1 ((t (:foreground "pale turquoise" :underline t))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
     (custom-link ((t (:foreground "cyan1" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-modified-face ((t (:background "blue" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-saved-face ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-set-face ((t (:background "white" :foreground "blue"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-state-face ((t (:foreground "light salmon"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-variable-tag-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (custom-visibility ((t (:foreground "cyan1" :underline t :height 0.8))))
     (diary ((t (:foreground "yellow1"))))
     (diary-face ((t (:foreground "red"))))
     (diff-added ((t (:background "#335533"))))
     (diff-changed ((t (nil))))
     (diff-context ((t (:foreground "#dddddd"))))
     (diff-file-header ((t (:bold t :background "grey60" :weight bold))))
     (diff-function ((t (:background "grey45"))))
     (diff-header ((t (:background "grey45"))))
     (diff-hunk-header ((t (:background "grey45"))))
     (diff-index ((t (:bold t :background "grey60" :weight bold))))
     (diff-indicator-added ((t (:background "#335533"))))
     (diff-indicator-changed ((t (nil))))
     (diff-indicator-removed ((t (:background "#553333"))))
     (diff-nonexistent ((t (:bold t :background "grey60" :weight bold))))
     (diff-refine-added ((t (:background "#22aa22"))))
     (diff-refine-changed ((t (:background "#aaaa22"))))
     (diff-refine-removed ((t (:background "#aa2222"))))
     (diff-removed ((t (:background "#553333"))))
     (dired-directory ((t (:bold t :foreground "aquamarine" :weight bold))))
     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-face-executable ((t (:foreground "green yellow"))))
     (dired-face-flagged ((t (:foreground "tomato"))))
     (dired-face-marked ((t (:foreground "light salmon"))))
     (dired-face-permissions ((t (:foreground "aquamarine"))))
     (dired-flagged ((t (:bold t :foreground "Pink" :weight bold))))
     (dired-header ((t (:bold t :foreground "sky blue" :weight bold))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "pale green"))))
     (dired-marked ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (dired-perm-write ((t (:foreground "light blue"))))
     (dired-symlink ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (dired-warning ((t (:bold t :foreground "Red" :weight bold))))
     (diredp-autofile-name ((t (:background "#111313F03181"))))
     (diredp-compressed-file-name ((t (:foreground "Blue"))))
     (diredp-compressed-file-suffix ((t (:foreground "Blue"))))
     (diredp-date-time ((t (:foreground "#74749A9AF7F7"))))
     (diredp-deletion ((t (:background "Red" :foreground "Yellow"))))
     (diredp-deletion-file-name ((t (:foreground "Red"))))
     (diredp-dir-heading ((t (:background "#00003F3F3434" :foreground "Yellow"))))
     (diredp-dir-name ((t (:background "#2C2C2C2C2C2C" :foreground "#7474FFFFFFFF"))))
     (diredp-dir-priv ((t (:background "#2C2C2C2C2C2C" :foreground "#7474FFFFFFFF"))))
     (diredp-exec-priv ((t (:background "#4F4F3B3B2121"))))
     (diredp-executable-tag ((t (:foreground "Red"))))
     (diredp-file-name ((t (:foreground "Yellow"))))
     (diredp-file-suffix ((t (:foreground "#7474FFFF7474"))))
     (diredp-flag-mark ((t (:background "#7575D4D41D1D" :foreground "Blue"))))
     (diredp-flag-mark-line ((t (:background "#787831311414"))))
     (diredp-ignored-file-name ((t (:foreground "#C29D6F156F15"))))
     (diredp-link-priv ((t (:foreground "#00007373FFFF"))))
     (diredp-mode-line-flagged ((t (:foreground "Red"))))
     (diredp-mode-line-marked ((t (:foreground "DarkViolet"))))
     (diredp-no-priv ((t (:background "#2C2C2C2C2C2C"))))
     (diredp-number ((t (:foreground "#FFFFFFFF7474"))))
     (diredp-other-priv ((t (:background "#111117175555"))))
     (diredp-rare-priv ((t (:background "#FFFF00008080" :foreground "Green"))))
     (diredp-read-priv ((t (:background "#999932325555"))))
     (diredp-symlink ((t (:foreground "#00007373FFFF"))))
     (diredp-tagged-autofile-name ((t (:background "#328C0411328C"))))
     (diredp-write-priv ((t (:background "#25258F8F2929"))))
     (ediff-current-diff-A ((t (:background "#553333"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed"))))
     (ediff-current-diff-B ((t (:background "#335533"))))
     (ediff-current-diff-C ((t (:background "#888833"))))
     (ediff-even-diff-A ((t (:background "light grey"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey"))))
     (ediff-even-diff-B ((t (:background "Grey"))))
     (ediff-even-diff-C ((t (:background "light grey"))))
     (ediff-fine-diff-A ((t (:background "#aa2222"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green"))))
     (ediff-fine-diff-B ((t (:background "#22aa22"))))
     (ediff-fine-diff-C ((t (:background "#aaaa22"))))
     (ediff-odd-diff-A ((t (:background "Grey"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40"))))
     (ediff-odd-diff-B ((t (:background "light grey"))))
     (ediff-odd-diff-C ((t (:background "Grey"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (erc-action-face ((t (nil))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "pale green"))))
     (erc-error-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-highlight-face ((t (:bold t :foreground "pale green" :weight bold))))
     (erc-input-face ((t (:foreground "light blue"))))
     (erc-inverse-face ((t (:background "steel blue"))))
     (erc-notice-face ((t (:foreground "light salmon"))))
     (erc-pal-face ((t (:foreground "pale green"))))
     (erc-prompt-face ((t (:bold t :foreground "light blue" :weight bold))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-archive-face ((t (:bold t :foreground "medium purple" :weight bold))))
     (eshell-ls-backup-face ((t (:foreground "dim gray"))))
     (eshell-ls-clutter-face ((t (:foreground "dim gray"))))
     (eshell-ls-directory-face ((t (:bold t :foreground "medium slate blue" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (eshell-ls-missing-face ((t (:foreground "black"))))
     (eshell-ls-picture-face ((t (:foreground "violet"))))
     (eshell-ls-product-face ((t (:foreground "light steel blue"))))
     (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
     (eshell-ls-special-face ((t (:foreground "gold"))))
     (eshell-ls-symlink-face ((t (:foreground "white"))))
     (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
     (eshell-prompt-face ((t (:bold t :foreground "light sky blue" :weight bold))))
     (evil-ex-commands ((t (:italic t :underline t :slant italic))))
     (evil-ex-info ((t (:italic t :foreground "red" :slant italic))))
     (evil-ex-lazy-highlight ((t (:background "paleturquoise4"))))
     (evil-ex-search ((t (:background "slate blue"))))
     (evil-ex-substitute-matches ((t (:background "paleturquoise4"))))
     (evil-ex-substitute-replacement ((t (:foreground "red" :underline t))))
     (excerpt ((t (:italic t :slant italic))))
     (ffap ((t (:background "dark slate blue" :foreground "light blue"))))
     (fg:erc-color-face0 ((t (:foreground "white"))))
     (fg:erc-color-face1 ((t (:foreground "beige"))))
     (fg:erc-color-face10 ((t (:foreground "pale goldenrod"))))
     (fg:erc-color-face11 ((t (:foreground "light goldenrod yellow"))))
     (fg:erc-color-face12 ((t (:foreground "light yellow"))))
     (fg:erc-color-face13 ((t (:foreground "yellow"))))
     (fg:erc-color-face14 ((t (:foreground "light goldenrod"))))
     (fg:erc-color-face15 ((t (:foreground "lime green"))))
     (fg:erc-color-face2 ((t (:foreground "lemon chiffon"))))
     (fg:erc-color-face3 ((t (:foreground "light cyan"))))
     (fg:erc-color-face4 ((t (:foreground "powder blue"))))
     (fg:erc-color-face5 ((t (:foreground "sky blue"))))
     (fg:erc-color-face6 ((t (:foreground "dark sea green"))))
     (fg:erc-color-face7 ((t (:foreground "pale green"))))
     (fg:erc-color-face8 ((t (:foreground "medium spring green"))))
     (fg:erc-color-face9 ((t (:foreground "khaki"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "courier"))))
     (fixed-pitch-serif ((t (:family "Monospace Serif"))))
     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "aquamarine"))))
     (font-lock-comment-delimiter-face ((t (:foreground "light blue"))))
     (font-lock-comment-face ((t (:foreground "light blue"))))
     (font-lock-constant-face ((t (:foreground "pale green"))))
     (font-lock-doc-face ((t (:foreground "light sky blue"))))
     (font-lock-doc-string-face ((t (:foreground "sky blue"))))
     (font-lock-function-name-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "aquamarine"))))
     (font-lock-reference-face ((t (:foreground "pale green"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "light sky blue"))))
     (font-lock-type-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (font-lock-variable-name-face ((t (:bold t :foreground "turquoise" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
     (fringe ((t (:background "Grey15"))))
     (git-commit-comment-action ((t (:bold t :foreground "turquoise" :weight bold))))
     (git-commit-comment-branch ((t (:bold t :weight bold :foreground "turquoise"))))
     (git-commit-comment-detached ((t (:bold t :foreground "turquoise" :weight bold))))
     (git-commit-comment-file ((t (:foreground "light sky blue"))))
     (git-commit-comment-heading ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (git-commit-known-pseudo-header ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (git-commit-nonempty-second-line ((t (:bold t :weight bold :foreground "Red"))))
     (git-commit-note ((t (:foreground "light sky blue"))))
     (git-commit-overlong-summary ((t (:bold t :weight bold :foreground "Red"))))
     (git-commit-pseudo-header ((t (:foreground "light sky blue"))))
     (git-commit-summary ((t (:bold t :weight bold :foreground "sky blue"))))
     (glyphless-char ((t (:height 0.6))))
     (gnus-cite-face-1 ((t (:foreground "LightSalmon"))))
     (gnus-cite-face-2 ((t (:foreground "Khaki"))))
     (gnus-cite-face-3 ((t (:foreground "Coral"))))
     (gnus-cite-face-4 ((t (:foreground "yellow green"))))
     (gnus-cite-face-5 ((t (:foreground "dark khaki"))))
     (gnus-cite-face-6 ((t (:foreground "bisque"))))
     (gnus-cite-face-7 ((t (:foreground "peru"))))
     (gnus-cite-face-8 ((t (:foreground "light coral"))))
     (gnus-cite-face-9 ((t (:foreground "plum"))))
     (gnus-emphasis-bold ((t (:bold t :weight bold))))
     (gnus-emphasis-bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (gnus-emphasis-highlight-words ((t (:background "black" :foreground "yellow"))))
     (gnus-emphasis-italic ((t (:italic t :slant italic))))
     (gnus-emphasis-strikethru ((t (nil))))
     (gnus-emphasis-underline ((t (:underline t))))
     (gnus-emphasis-underline-bold ((t (:bold t :underline t :weight bold))))
     (gnus-emphasis-underline-bold-italic ((t (:italic t :bold t :underline t :slant italic :weight bold))))
     (gnus-emphasis-underline-italic ((t (:italic t :underline t :slant italic))))
     (gnus-group-mail-1-empty-face ((t (:foreground "White"))))
     (gnus-group-mail-1-face ((t (:bold t :foreground "White" :weight bold))))
     (gnus-group-mail-2-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-mail-2-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-mail-3-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-mail-low-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-mail-low-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-group-news-1-empty-face ((t (:foreground "White"))))
     (gnus-group-news-1-face ((t (:bold t :foreground "White" :weight bold))))
     (gnus-group-news-2-empty-face ((t (:foreground "light cyan"))))
     (gnus-group-news-2-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-news-3-empty-face ((t (:foreground "LightBlue"))))
     (gnus-group-news-3-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-group-news-4-empty-face ((t (:foreground "Aquamarine"))))
     (gnus-group-news-4-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-group-news-5-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-5-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-6-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-6-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-group-news-low-empty-face ((t (:foreground "MediumAquamarine"))))
     (gnus-group-news-low-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-header-content-face ((t (:foreground "LightSkyBlue3"))))
     (gnus-header-from-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "LightBlue" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
     (gnus-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-server-agent-face ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (gnus-server-closed-face ((t (:italic t :foreground "Light Steel Blue" :slant italic))))
     (gnus-server-denied-face ((t (:bold t :foreground "Pink" :weight bold))))
     (gnus-server-offline-face ((t (:bold t :foreground "Yellow" :weight bold))))
     (gnus-server-opened-face ((t (:bold t :foreground "Green1" :weight bold))))
     (gnus-signature-face ((t (:foreground "Grey"))))
     (gnus-splash-face ((t (:foreground "ForestGreen"))))
     (gnus-summary-cancelled-face ((t (:background "Black" :foreground "Yellow"))))
     (gnus-summary-high-ancient-face ((t (:bold t :foreground "MediumAquamarine" :weight bold))))
     (gnus-summary-high-read-face ((t (:bold t :foreground "Aquamarine" :weight bold))))
     (gnus-summary-high-ticked-face ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (gnus-summary-high-unread-face ((t (:italic t :bold t :foreground "beige" :slant italic :weight bold))))
     (gnus-summary-low-ancient-face ((t (:italic t :foreground "DimGray" :slant italic))))
     (gnus-summary-low-read-face ((t (:foreground "slate gray"))))
     (gnus-summary-low-ticked-face ((t (:foreground "Pink"))))
     (gnus-summary-low-unread-face ((t (:foreground "LightGray"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "MediumAquamarine"))))
     (gnus-summary-normal-read-face ((t (:foreground "Aquamarine"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "LightSalmon"))))
     (gnus-summary-normal-unread-face ((t (nil))))
     (gnus-summary-selected-face ((t (:underline t))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:foreground "sky blue"))))
     (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
     (highline-face ((t (:background "DeepSkyBlue4"))))
     (holiday ((t (:background "chocolate4"))))
     (holiday-face ((t (:background "pink"))))
     (hydra-face-amaranth ((t (:bold t :foreground "#E52B50" :weight bold))))
     (hydra-face-blue ((t (:bold t :foreground "#8ac6f2" :weight bold))))
     (hydra-face-pink ((t (:bold t :foreground "#FF6EB4" :weight bold))))
     (hydra-face-red ((t (:bold t :foreground "#FF0000" :weight bold))))
     (hydra-face-teal ((t (:bold t :foreground "#367588" :weight bold))))
     (iedit-occurrence ((t (:background "dark slate blue" :foreground "light blue"))))
     (iedit-read-only-occurrence ((t (:background "DarkSlateBlue"))))
     (info-header-node ((t (:bold t :weight bold))))
     (info-header-xref ((t (:bold t :foreground "sky blue" :weight bold))))
     (info-index-match ((t (:background "RoyalBlue3"))))
     (info-menu-header ((t (:bold t :weight bold :family "helv"))))
     (info-menu-star ((t (:foreground "red1" :underline t))))
     (info-node ((t (:bold t :weight bold))))
     (info-title-1 ((t (:bold t :weight bold :height 2.9859839999999997 :family "helv"))))
     (info-title-2 ((t (:bold t :weight bold :height 1.728 :family "helv"))))
     (info-title-3 ((t (:bold t :weight bold :height 1.2 :family "helv"))))
     (info-title-4 ((t (:bold t :weight bold :family "helv"))))

     (info-xref ((t (:bold t :foreground "sky blue" :weight bold))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "slate blue"))))
     (isearch-fail ((t (:background "red4"))))
     (italic ((t (:foreground "sky blue"))))
     (ivy-action ((t (:foreground "aquamarine"))))
     (ivy-confirm-face ((t (:background "#E4E4E4" :foreground "ForestGreen" :box nil))))
     (ivy-current-match ((t (:background "#65a7e2" :foreground "black"))))
     (ivy-cursor ((t (:background "black" :foreground "white"))))
     (ivy-highlight-face ((t (:foreground "light blue" :background "dark slate blue"))))
     (ivy-match-required-face ((t (:background "#E4E4E4" :foreground "red" :box nil))))
     (ivy-minibuffer-match-face-1 ((t (:background "#555555"))))
     (ivy-minibuffer-match-face-2 ((t (:bold t :background "#777777" :weight bold))))
     (ivy-minibuffer-match-face-3 ((t (:bold t :background "#7777ff" :weight bold))))
     (ivy-minibuffer-match-face-4 ((t (:bold t :background "#8a498a" :weight bold))))
     (ivy-modified-buffer ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (ivy-remote ((t (:foreground "#7B6BFF"))))
     (ivy-subdir ((t (:bold t :foreground "aquamarine" :weight bold))))
     (ivy-virtual ((t (:foreground "aquamarine"))))
     (jde-bug-breakpoint-cursor ((t (:background "brown" :foreground "cyan"))))
     (jde-bug-breakpoint-marker ((t (:background "yellow" :foreground "red"))))
     (jde-java-font-lock-api-face ((t (:foreground "light goldenrod"))))
     (jde-java-font-lock-bold-face ((t (:bold t :weight bold))))
     (jde-java-font-lock-code-face ((t (nil))))
     (jde-java-font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (jde-java-font-lock-doc-tag-face ((t (:foreground "light coral"))))
     (jde-java-font-lock-italic-face ((t (:italic t :slant italic))))
     (jde-java-font-lock-link-face ((t (:foreground "blue" :underline t :slant normal))))
     (jde-java-font-lock-modifier-face ((t (:foreground "LightSteelBlue"))))
     (jde-java-font-lock-number-face ((t (:foreground "LightSalmon"))))
     (jde-java-font-lock-package-face ((t (:foreground "steelblue1"))))
     (jde-java-font-lock-pre-face ((t (nil))))
     (jde-java-font-lock-underline-face ((t (:underline t))))
     (js2-error ((t (:foreground "red"))))
     (js2-external-variable ((t (:foreground "orange"))))
     (js2-function-call ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (js2-function-param ((t (:foreground "SeaGreen"))))
     (js2-instance-member ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter ((t (:foreground "green"))))
     (js2-jsdoc-html-tag-name ((t (:foreground "yellow"))))
     (js2-jsdoc-tag ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value ((t (:foreground "PeachPuff3"))))
     (js2-object-property ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (js2-private-function-call ((t (:foreground "goldenrod"))))
     (js2-private-member ((t (:foreground "PeachPuff3"))))
     (js2-warning ((t (:underline "orange"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linum ((t (:bold t :background "black" :foreground "brightblack" :weight bold))))
     (lispy-command-name-face ((t (:bold t :background "#333333" :foreground "aquamarine" :weight bold))))
     (lispy-cursor-face ((t (:background "white" :foreground "black"))))
     (lispy-face-hint ((t (:background "black" :foreground "#fff3bc"))))
     (lispy-face-key-nosel ((t (:italic t :background "black" :foreground "#fff3bc" :slant italic))))
     (lispy-face-key-sel ((t (:italic t :bold t :background "black" :foreground "#fff3bc" :slant italic :weight bold))))
     (lispy-face-opt-nosel ((t (:italic t :background "black" :foreground "#fff3bc" :slant italic))))
     (lispy-face-opt-sel ((t (:italic t :bold t :background "black" :foreground "#fff3bc" :slant italic :weight bold))))
     (lispy-face-req-nosel ((t (:background "black" :foreground "#fff3bc"))))
     (lispy-face-req-sel ((t (:bold t :background "black" :foreground "#fff3bc" :weight bold))))
     (lispy-face-rst-nosel ((t (:background "black" :foreground "#fff3bc"))))
     (lispy-face-rst-sel ((t (:bold t :background "black" :foreground "#fff3bc" :weight bold))))
     (lispy-test-face ((t (:background "black" :foreground "#fff3bc"))))
     (log-edit-header ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (log-edit-summary ((t (:bold t :weight bold :foreground "aquamarine"))))
     (log-edit-unknown-header ((t (:foreground "light blue"))))
     (lv-separator ((t (:background "grey30"))))
     (magit-bisect-bad ((t (:foreground "IndianRed4"))))
     (magit-bisect-good ((t (:foreground "DarkOliveGreen"))))
     (magit-bisect-skip ((t (:foreground "DarkGoldenrod"))))
     (magit-blame-date ((t (:foreground "white" :background "grey25"))))
     (magit-blame-hash ((t (:foreground "white" :background "grey25"))))
     (magit-blame-heading ((t (:background "grey25" :foreground "white"))))
     (magit-blame-name ((t (:foreground "white" :background "grey25"))))
     (magit-blame-summary ((t (:foreground "white" :background "grey25"))))
     (magit-branch-current ((t (:foreground "LightSkyBlue1" :box 1))))
     (magit-branch-local ((t (:foreground "LightSkyBlue1"))))
     (magit-branch-remote ((t (:foreground "DarkSeaGreen2"))))
     (magit-cherry-equivalent ((t (:foreground "magenta"))))
     (magit-cherry-unmatched ((t (:foreground "cyan"))))
     (magit-diff-added ((t (:background "#335533" :foreground "#ddffdd"))))
     (magit-diff-added-highlight ((t (:background "#336633" :foreground "#cceecc"))))
     (magit-diff-base ((t (:background "#555522" :foreground "#ffffcc"))))
     (magit-diff-base-highlight ((t (:background "#666622" :foreground "#eeeebb"))))
     (magit-diff-conflict-heading ((t (:foreground "grey70" :background "grey25"))))
     (magit-diff-context ((t (:foreground "grey70"))))
     (magit-diff-context-highlight ((t (:background "grey20" :foreground "grey70"))))
     (magit-diff-file-heading ((t (:bold t :weight bold))))
     (magit-diff-file-heading-highlight ((t (:background "grey20"))))
     (magit-diff-file-heading-selection ((t (:background "grey20" :foreground "LightSalmon3"))))
     (magit-diff-hunk-heading ((t (:background "grey25" :foreground "grey70"))))
     (magit-diff-hunk-heading-highlight ((t (:background "grey35" :foreground "grey70"))))
     (magit-diff-hunk-heading-selection ((t (:background "grey35" :foreground "LightSalmon3"))))
     (magit-diff-hunk-region ((t (:bold t :weight bold))))
     (magit-diff-lines-boundary ((t (:foreground "grey80" :background "salmon4"))))
     (magit-diff-lines-heading ((t (:background "salmon4" :foreground "grey80"))))
     (magit-diff-our ((t (:foreground "#ffdddd" :background "#553333"))))
     (magit-diff-our-highlight ((t (:foreground "#eecccc" :background "#663333"))))
     (magit-diff-removed ((t (:background "#553333" :foreground "#ffdddd"))))
     (magit-diff-removed-highlight ((t (:background "#663333" :foreground "#eecccc"))))
     (magit-diff-their ((t (:foreground "#ddffdd" :background "#335533"))))
     (magit-diff-their-highlight ((t (:foreground "#cceecc" :background "#336633"))))
     (magit-diff-whitespace-warning ((t (:background "indian red"))))
     (magit-diffstat-added ((t (:foreground "#448844"))))
     (magit-diffstat-removed ((t (:foreground "#aa4444"))))
     (magit-dimmed ((t (:foreground "grey50"))))
     (magit-filename ((t (:weight normal))))
     (magit-hash ((t (:foreground "grey40"))))
     (magit-head ((t (:foreground "LightSkyBlue1"))))
     (magit-header-line ((t (:bold t :weight bold :foreground "LightGoldenrod2"))))
     (magit-log-author ((t (:foreground "tomato"))))
     (magit-log-date ((t (:foreground "grey80"))))
     (magit-log-graph ((t (:foreground "grey80"))))
     (magit-popup-argument ((t (:bold t :weight bold :foreground "Red"))))
     (magit-popup-disabled-argument ((t (:foreground "grey70"))))
     (magit-popup-heading ((t (:bold t :weight bold :foreground "pale turquoise"))))
     (magit-popup-key ((t (:foreground "aquamarine"))))
     (magit-popup-option-value ((t (:foreground "light sky blue"))))
     (magit-process-ng ((t (:bold t :weight bold :foreground "red"))))
     (magit-process-ok ((t (:bold t :weight bold :foreground "green"))))
     (magit-reflog-amend ((t (:foreground "magenta"))))
     (magit-reflog-checkout ((t (:foreground "blue"))))
     (magit-reflog-cherry-pick ((t (:foreground "green"))))
     (magit-reflog-commit ((t (:foreground "green"))))
     (magit-reflog-merge ((t (:foreground "green"))))
     (magit-reflog-other ((t (:foreground "cyan"))))
     (magit-reflog-rebase ((t (:foreground "magenta"))))
     (magit-reflog-remote ((t (:foreground "cyan"))))
     (magit-reflog-reset ((t (:foreground "red"))))
     (magit-refname ((t (:foreground "grey80"))))
     (magit-refname-stash ((t (:foreground "grey80"))))
     (magit-refname-wip ((t (:foreground "grey80"))))
     (magit-section-heading ((t (:bold t :foreground "LightGoldenrod2" :weight bold))))
     (magit-section-heading-selection ((t (:foreground "LightSalmon3"))))
     (magit-section-highlight ((t (:background "grey20"))))
     (magit-section-secondary-heading ((t (:bold t :weight bold))))
     (magit-sequence-done ((t (:foreground "grey40"))))
     (magit-sequence-drop ((t (:foreground "IndianRed"))))
     (magit-sequence-head ((t (:foreground "LightSkyBlue1"))))
     (magit-sequence-onto ((t (:foreground "grey40"))))
     (magit-sequence-part ((t (:foreground "LightGoldenrod2"))))
     (magit-sequence-pick ((t (:family "DejaVu Sans Mono" :foundry "PfEd" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "Grey" :background "Grey15" :stipple nil :height 143))))
     (magit-sequence-stop ((t (:foreground "DarkSeaGreen2"))))
     (magit-signature-bad ((t (:bold t :foreground "red" :weight bold))))
     (magit-signature-error ((t (:foreground "firebrick3"))))
     (magit-signature-expired ((t (:foreground "orange"))))
     (magit-signature-expired-key ((t (:foreground "orange"))))
     (magit-signature-good ((t (:foreground "green"))))
     (magit-signature-revoked ((t (:foreground "violet red"))))
     (magit-signature-untrusted ((t (:foreground "cyan"))))
     (magit-tag ((t (:foreground "LightGoldenrod2"))))
     (makefile-space-face ((t (:background "hotpink"))))
     (match ((t (:background "RoyalBlue3"))))
     (mc/cursor-bar-face ((t (:background "#93a1a1" :height 1))))
     (mc/cursor-face ((t (nil))))
     (mc/region-face ((t (:background "DarkSlateBlue"))))
     (menu ((t (:background "MidnightBlue" :foreground "Grey"))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-cited-text-face ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-cc-face ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-name-face ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-other-face ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-subject-face ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-to-face ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-header-xheader-face ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-mml-face ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (message-separator-face ((t (:foreground "LightSkyBlue1"))))
     (minibuffer-prompt ((t (:background "#E4E4E4" :foreground "#585858" :box nil))))
     (mm-command-output ((t (:foreground "ForestGreen"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (mode-line-buffer-id ((t (:background "#E4E4E4" :foreground "#585858" :box nil :overline nil :underline nil))))
     (mode-line-buffer-id-inactive ((t (:background "#E4E4E4" :foreground "#585858" :box nil :overline nil :underline nil))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "#E4E4E4" :foreground "#585858" :box nil :overline nil :underline nil))))
     (modeline ((t (:background "white" :foreground "DeepSkyBlue3"))))
     (modeline-mousable ((t (:background "white" :foreground "DeepSkyBlue3"))))
     (modeline-mousable-minor-mode ((t (:background "white" :foreground "DeepSkyBlue3"))))
     (mouse ((t (:background "Grey"))))
     (next-error ((t (:background "DarkSlateBlue"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (org-agenda-calendar-event ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (org-agenda-calendar-sexp ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (org-agenda-clocking ((t (:background "steel blue"))))
     (org-agenda-column-dateline ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-diary ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-filter-category ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (org-agenda-filter-regexp ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (org-agenda-filter-tags ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (org-agenda-restriction-lock ((t (:background "#1C1C1C"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "grey70"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:foreground "light blue"))))
     (org-block-end-line ((t (:foreground "light blue"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-checkbox-statistics-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "Cyan" :underline t))))
     (org-date-selected ((t (:background "Pink"))))
     (org-default ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-habit-alert-face ((t (:background "gold"))))
     (org-habit-alert-future-face ((t (:background "darkgoldenrod"))))
     (org-habit-clear-face ((t (:background "blue"))))
     (org-habit-clear-future-face ((t (:background "midnightblue"))))
     (org-habit-overdue-face ((t (:background "firebrick"))))
     (org-habit-overdue-future-face ((t (:background "darkred"))))
     (org-habit-ready-face ((t (:background "forestgreen"))))
     (org-habit-ready-future-face ((t (:background "darkgreen"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "Grey15"))))
     (org-latex-and-related ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground "aquamarine" :weight bold))))
     (org-level-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (org-level-3 ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-level-4 ((t (:foreground "light blue"))))
     (org-level-5 ((t (:bold t :foreground "sky blue" :weight bold))))
     (org-level-6 ((t (:foreground "pale green"))))
     (org-level-7 ((t (:foreground "aquamarine"))))
     (org-level-8 ((t (:foreground "light sky blue"))))
     (org-link ((t (:foreground "cyan1" :underline t))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:foreground "burlywood"))))
     (org-meta-line ((t (:foreground "light blue"))))
     (org-mode-line-clock ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (org-mode-line-clock-overrun ((t (:background "red" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (org-priority ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey70"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-tag-group ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-term/definition-face ((t (:bold t :background "#888" :foreground "black" :weight bold))))
     (org-term/usage-face ((t (:bold t :background "#666" :foreground "#333" :weight bold))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:foreground "grey70"))))
     (org-verse ((t (:foreground "grey70"))))
     (org-warning ((t (:bold t :foreground "Red" :weight bold))))
     (outline-1 ((t (:bold t :foreground "aquamarine" :weight bold))))
     (outline-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (outline-3 ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (outline-4 ((t (:foreground "light blue"))))
     (outline-5 ((t (:bold t :foreground "sky blue" :weight bold))))
     (outline-6 ((t (:foreground "pale green"))))
     (outline-7 ((t (:foreground "aquamarine"))))
     (outline-8 ((t (:foreground "light sky blue"))))
     (package-description ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (package-help-section-name ((t (:bold t :weight bold))))
     (package-name ((t (:foreground "cyan1" :underline t))))
     (package-status-avail-obso ((t (:foreground "light blue"))))
     (package-status-available ((t (:stipple nil :background "Grey15" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 112 :width normal :foundry "PfEd" :family "DejaVu Sans Mono"))))
     (package-status-built-in ((t (:foreground "aquamarine"))))
     (package-status-dependency ((t (:foreground "light blue"))))
     (package-status-disabled ((t (:bold t :foreground "Red" :weight bold))))
     (package-status-external ((t (:foreground "aquamarine"))))
     (package-status-held ((t (:foreground "pale green"))))
     (package-status-incompat ((t (:foreground "light blue"))))
     (package-status-installed ((t (:foreground "light blue"))))
     (package-status-new ((t (:bold t :weight bold))))
     (package-status-unsigned ((t (:bold t :foreground "Red" :weight bold))))
     (powerline-active1 ((t (:background "grey22" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (powerline-active2 ((t (:background "grey40" :foreground "black" :box (:line-width -1 :style released-button) :overline nil :underline nil))))
     (powerline-inactive1 ((t (:background "#E4E4E4" :foreground "#585858"))))
     (powerline-inactive2 ((t (:background "#466D79" :foreground "#E4E4E4"))))
     (query-replace ((t (:background "slate blue"))))
     (rectangle-preview ((t (:background "DarkSlateBlue"))))
     (region ((t (:background "DarkSlateBlue"))))
     (scroll-bar ((t (:background "grey75"))))
     (secondary-selection ((t (:background "steel blue"))))
     (semantic-dirty-token-face ((t (:background "gray10"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (sgml-namespace ((t (:foreground "aquamarine"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "light slate blue" :foreground "white"))))
     (show-paren-mismatch ((t (:background "red" :foreground "white"))))
     (smerge-base ((t (:background "#888833"))))
     (smerge-markers ((t (:background "grey30"))))
     (smerge-mine ((t (:background "#553333"))))
     (smerge-other ((t (:background "#335533"))))
     (smerge-refined-added ((t (:background "#22aa22"))))
     (smerge-refined-changed ((t (nil))))
     (smerge-refined-removed ((t (:background "#aa2222"))))
     (speedbar-button-face ((t (:foreground "seashell2"))))
     (speedbar-directory-face ((t (:foreground "seashell3"))))
     (speedbar-file-face ((t (:foreground "seashell4"))))
     (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
     (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "antique white"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (swiper-line-face ((t (:background "dark slate blue" :foreground "light blue"))))
     (swiper-match-face-1 ((t (:background "paleturquoise4"))))
     (swiper-match-face-2 ((t (:background "slate blue"))))
     (swiper-match-face-3 ((t (:background "RoyalBlue3"))))
     (swiper-match-face-4 ((t (:background "red4"))))
     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "indian red"))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (underline ((t (:underline t))))
     (undo-tree-visualizer-active-branch-face ((t (:bold t :foreground "white" :weight bold))))
     (undo-tree-visualizer-current-face ((t (:foreground "red"))))
     (undo-tree-visualizer-default-face ((t (:foreground "gray"))))
     (undo-tree-visualizer-register-face ((t (:foreground "yellow"))))
     (undo-tree-visualizer-unmodified-face ((t (:foreground "cyan"))))
     (variable-pitch ((t (:family "helv"))))
     (vc-conflict-state ((t (nil))))
     (vc-edited-state ((t (nil))))
     (vc-locally-added-state ((t (nil))))
     (vc-locked-state ((t (nil))))
     (vc-missing-state ((t (nil))))
     (vc-needs-update-state ((t (nil))))
     (vc-removed-state ((t (nil))))
     (vc-state-base ((t (nil))))
     (vc-up-to-date-state ((t (nil))))
     (vertical-border ((t (nil))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (which-key-command-description-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (which-key-group-description-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (which-key-highlighted-command-face ((t (:bold t :foreground "aquamarine" :underline t :weight bold))))
     (which-key-key-face ((t (:foreground "pale green"))))
     (which-key-local-map-description-face ((t (:bold t :foreground "aquamarine" :weight bold))))
     (which-key-note-face ((t (:foreground "light blue"))))
     (which-key-separator-face ((t (:foreground "light blue"))))
     (which-key-special-key-face ((t (:bold t :background "pale green" :weight bold))))
     (whitespace-big-indent ((t (:background "red" :foreground "firebrick"))))
     (whitespace-empty ((t (:background "yellow" :foreground "firebrick"))))
     (whitespace-hspace ((t (:background "grey24" :foreground "gray30"))))
     (whitespace-indentation ((t (:background "grey40" :foreground "grey24"))))
     (whitespace-line ((t (:background "gray20"))))
     (whitespace-newline ((t (:foreground "darkgray" :weight normal))))
     (whitespace-space ((t (:foreground "gray35"))))
     (whitespace-space-after-tab ((t (:background "grey40" :foreground "grey24"))))
     (whitespace-space-before-tab ((t (:background "grey40" :foreground "grey24"))))
     (whitespace-tab ((t (:background "grey22" :foreground "gray15"))))
     (whitespace-trailing ((t (:bold t :foreground "red" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red"))))
     (widget-documentation ((t (:foreground "light blue"))))
     (widget-field ((t (:background "RoyalBlue4" :foreground "wheat"))))
     (widget-inactive ((t (:foreground "dim gray"))))
     (widget-single-line-field ((t (:background "slate blue" :foreground "wheat"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40"))))
     (woman-addition ((t (:foreground "aquamarine"))))
     (woman-bold ((t (:bold t :foreground "sky blue" :weight bold))))
     (woman-bold-face ((t (:bold t :foreground "sky blue" :weight bold))))
     (woman-italic ((t (:foreground "deep sky blue"))))
     (woman-italic-face ((t (:foreground "deep sky blue"))))
     (woman-unknown ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (woman-unknown-face ((t (:bold t :foreground "LightSalmon" :weight bold))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "DarkSlateBlue"))))
     (zmacs-region ((t (:background "DarkSlateBlue")))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
